server:
  port: 8080
  address: 0.0.0.0
  tomcat:
    connection-timeout: 60000
    max-http-form-post-size: 100MB

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/file_storage_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


app:
  security:
    jwt:
      secret: ${JWT_SECRET:super-secret-key}
      expiration: 86400000

  storage:
    location: ${STORAGE_LOCATION:./uploads}

  cors:
    allowed-origins: http://localhost:8081

management:
  endpoints:
    web:
      exposure:
        include: health


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    ru.netology.filestorage: DEBUG
